name: Go

on:
  push:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: 1.17

    - name: Install libsoundio (Linux)
      run: apt install libsoundio-dev
        
    - name: Build
      run: go build -o ./alapi ./cmd/alapi

    - name: Test
      run: go test -v ./...
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: alapi-linux
        path: ./alapi
 
 
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: 1.17

    - name: Install libsoundio (macOS)
      run: brew install libsoundio
      
    - name: Build
      run: go build -o ./alapi ./cmd/alapi

    - name: Test
      run: go test -v ./...
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: alapi-macos
        path: ./alapi
  
  
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: 1.17

    - name: Install libsoundio (Windows)
      run: |
        mkdir lib
        wget "https://github.com/cameronmaske/libsoundio-binaries/raw/master/win/x64/libsoundio.dll" -outfile "lib/libsoundio.dll"
        wget "https://github.com/cameronmaske/libsoundio-binaries/raw/master/win/x64/libsoundio.lib" -outfile "lib/libsoundio.lib"
        echo ("$(pwd)/lib") >> $GITHUB_PATH
        
    - name: Build
      run: go build -o ./alapi.exe ./cmd/alapi

    - name: Test
      run: go test -v ./...
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: alapi-windows
        path: ./alapi.exe
